gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 7200 # 2h
    single_use: true
    ttl_update: true
    return_expiration: true

    # Use cookies for the refresh token
    cookie:
        enabled: true
        remove_token_from_body: false
        # Cookie parameters
        http_only: true
        same_site: strict
        secure: true
        path: /api/token
        domain: null